// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QMSWebApplication.BackendServer.Data;

#nullable disable

namespace QMSWebApplication.BackendServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407035722_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("KnowledgeBaseSepence");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Characteristics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DataType")
                        .HasColumnType("int")
                        .HasColumnName("DataType");

                    b.Property<int?>("Decimals")
                        .HasColumnType("int")
                        .HasColumnName("Decimals");

                    b.Property<int?>("DefectRateLimit")
                        .HasColumnType("int")
                        .HasColumnName("DefectRateLimit");

                    b.Property<int?>("EmailEventModel")
                        .HasColumnType("int")
                        .HasColumnName("EmailEventModel");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<int?>("MeaTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MeaTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("ProcessId");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Unit");

                    b.HasKey("Id");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.CommandInFuntions", b =>
                {
                    b.Property<int>("CommandId")
                        .HasColumnType("int")
                        .HasColumnName("CommandId");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int")
                        .HasColumnName("FunctionId");

                    b.HasKey("CommandId", "FunctionId");

                    b.ToTable("CommandInFuntions");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Commands", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.EmailServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("EnabledSSL")
                        .HasColumnType("bit")
                        .HasColumnName("EnabledSSL");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("SMTPHost")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SMTPHost");

                    b.Property<int?>("SMTPPort")
                        .HasColumnType("int")
                        .HasColumnName("SMTPPort");

                    b.HasKey("Id");

                    b.ToTable("EmailServer");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.EventLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Description");

                    b.Property<string>("EventCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("EventCode");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("EventTime");

                    b.Property<string>("Station")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Station");

                    b.HasKey("Id");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.EventRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacteristicId")
                        .HasColumnType("int")
                        .HasColumnName("CharacteristicId");

                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RoleId");

                    b.HasKey("Id");

                    b.ToTable("EventRoles");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Functions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentId");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.InspectionPlanData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacteristicId")
                        .HasColumnType("int")
                        .HasColumnName("CharacteristicId");

                    b.Property<double?>("CpkMax")
                        .HasColumnType("float")
                        .HasColumnName("CpkMax");

                    b.Property<double?>("CpkMin")
                        .HasColumnType("float")
                        .HasColumnName("CpkMin");

                    b.Property<bool?>("DataEntry")
                        .HasColumnType("bit")
                        .HasColumnName("DataEntry");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<bool?>("EnabledCpkControl")
                        .HasColumnType("bit")
                        .HasColumnName("EnabledCpkControl");

                    b.Property<bool?>("EnabledSPCChart")
                        .HasColumnType("bit")
                        .HasColumnName("EnabledSPCChart");

                    b.Property<int?>("InspPlanSubId")
                        .HasColumnType("int")
                        .HasColumnName("InspPlanSubId");

                    b.Property<double?>("LCL")
                        .HasColumnType("float")
                        .HasColumnName("LCL");

                    b.Property<double?>("LSL")
                        .HasColumnType("float")
                        .HasColumnName("LSL");

                    b.Property<string>("Notes")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Notes");

                    b.Property<double?>("PercentControlLimit")
                        .HasColumnType("float")
                        .HasColumnName("PercentControlLimit");

                    b.Property<double?>("UCL")
                        .HasColumnType("float")
                        .HasColumnName("UCL");

                    b.Property<double?>("USL")
                        .HasColumnType("float")
                        .HasColumnName("USL");

                    b.HasKey("Id");

                    b.ToTable("InspectionPlanData");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.InspectionPlanSubs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<int>("InspPlanId")
                        .HasColumnType("int")
                        .HasColumnName("InspPlanId");

                    b.Property<int>("PlanState")
                        .HasColumnType("int")
                        .HasColumnName("PlanState");

                    b.Property<int>("PlanTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PlanTypeId");

                    b.Property<DateTimeOffset>("UploadedDateTime")
                        .HasColumnType("DateTimeOffset")
                        .HasColumnName("UploadedDateTime");

                    b.HasKey("Id");

                    b.ToTable("InspectionPlanSubs");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.InspectionPlanTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacteristicId")
                        .HasColumnType("int")
                        .HasColumnName("CharacteristicId");

                    b.Property<int?>("InspPlanId")
                        .HasColumnType("int")
                        .HasColumnName("InspPlanId");

                    b.Property<int?>("PlanState")
                        .HasColumnType("int")
                        .HasColumnName("PlanState");

                    b.Property<int?>("PlanTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PlanTypeId");

                    b.Property<DateTimeOffset?>("UploadedDateTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("UploadedDateTime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("InspectionPlanTracking");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.InspectionPlanTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("InspectionPlanTypes");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.InspectionPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<DateTimeOffset?>("ModifiedDateTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("ModifiedDateTime");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<DateTimeOffset?>("UploadedDateTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("UploadedDateTime");

                    b.Property<int?>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("InspectionPlans");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.JobDecisions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ColorCode");

                    b.Property<string>("Decision")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Decision");

                    b.HasKey("Id");

                    b.ToTable("JobDecisions");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Jobs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<string>("JobCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("JobCode");

                    b.Property<int?>("JobDecisionId")
                        .HasColumnType("int")
                        .HasColumnName("JobDecisionId");

                    b.Property<int?>("OutputQuantity")
                        .HasColumnType("int")
                        .HasColumnName("OutputQuantity");

                    b.Property<string>("POCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("POCode");

                    b.Property<int?>("PlannedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("PlannedQuantity");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<string>("SOCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SOCode");

                    b.Property<DateTimeOffset?>("UploadedDateTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("UploadedDateTime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.ProcessLines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LineCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LineCode");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("ProcessId");

                    b.HasKey("Id");

                    b.ToTable("ProcessLine");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Processes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Process");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.ProductionAreas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ProductionAreas");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.ProductionPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CNCLatheMachine")
                        .HasColumnType("int")
                        .HasColumnName("CNCLatheMachine");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Ennabled");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("EndTime");

                    b.Property<int?>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("JobId");

                    b.Property<int?>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineId");

                    b.Property<string>("LotInform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LotInform");

                    b.Property<string>("MaterialInform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaterialInform");

                    b.Property<DateTimeOffset?>("ModifiedDateTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("ModifiedDateTime");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Notes");

                    b.Property<int?>("PlannedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("PlannedQuantity");

                    b.Property<DateTimeOffset?>("ProductionDate")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("ProductionDate");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("StartTime");

                    b.Property<DateTimeOffset>("UploadedDateTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("UploadedDateTime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("ProductionData");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    b.Property<int?>("CavityQuantity")
                        .HasColumnType("int")
                        .HasColumnName("CavityQuantity");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CustomerName");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<int?>("InspPlanId")
                        .HasColumnType("int")
                        .HasColumnName("InspPlanId");

                    b.Property<string>("ModelInternal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModelInternal");

                    b.Property<int?>("MoldQuantity")
                        .HasColumnType("int")
                        .HasColumnName("MoldQuantity");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Notes");

                    b.Property<int?>("VialFixture")
                        .HasColumnType("int")
                        .HasColumnName("VialFixture");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntLevel")
                        .HasColumnType("int")
                        .HasColumnName("intLevel");

                    b.Property<int>("IntRoleID")
                        .HasColumnType("int")
                        .HasColumnName("intRoleID");

                    b.Property<int?>("IntRoleUser")
                        .HasColumnType("int")
                        .HasColumnName("intRoleUser");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StrDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("strDescription");

                    b.Property<string>("StrRoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strRoleName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.SampleTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("MeasureType");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Samples", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CavityId")
                        .HasColumnType("int")
                        .HasColumnName("CavityId");

                    b.Property<int?>("CharacteristicId")
                        .HasColumnType("int")
                        .HasColumnName("CharacteristicId");

                    b.Property<string>("CharacteristicRange")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("CharacteristicRange");

                    b.Property<string>("CharacteristicValue")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("CharacteristicValue");

                    b.Property<int?>("DataCollection")
                        .HasColumnType("int")
                        .HasColumnName("DataCollection");

                    b.Property<int?>("EmailSent")
                        .HasColumnType("int")
                        .HasColumnName("EmailSent");

                    b.Property<int?>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("JobId");

                    b.Property<int?>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineId");

                    b.Property<DateTimeOffset?>("MeasuredDateTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("MeasuredDateTime");

                    b.Property<int?>("MoldId")
                        .HasColumnType("int")
                        .HasColumnName("MoldId");

                    b.Property<string>("Notes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Notes");

                    b.Property<int?>("OutputQuantity")
                        .HasColumnType("int")
                        .HasColumnName("OutputQuantity");

                    b.Property<int?>("PlanTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PlanTypeId");

                    b.Property<int?>("ProductionId")
                        .HasColumnType("int")
                        .HasColumnName("ProductionId");

                    b.Property<int?>("SampleIndex")
                        .HasColumnType("int")
                        .HasColumnName("SampleIndex");

                    b.Property<int?>("SampleQuantity")
                        .HasColumnType("int")
                        .HasColumnName("SampleQuantity");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset?>("UploadedDateTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("UploadedDateTime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.Shifts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("EndTime");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.TVDisplays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("TVDisplay");
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DtLastActivityTime")
                        .HasColumnType("datetime")
                        .HasColumnName("dtLastActivityTime");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IntEnable")
                        .HasColumnType("int")
                        .HasColumnName("intEnable");

                    b.Property<int>("IntUserID")
                        .HasColumnType("int")
                        .HasColumnName("intUserID");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strDepartment");

                    b.Property<string>("StrEmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strEmailAddress");

                    b.Property<string>("StrFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strFullName");

                    b.Property<string>("StrPassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strPassword");

                    b.Property<string>("StrRoleID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strRoleID");

                    b.Property<string>("StrSelectedAreaID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strSelectedAreaID");

                    b.Property<string>("StrStaffID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strStaffID");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QMSWebApplication.BackendServer.Data.Entities.WebSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("EndTime");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SessionId");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("DateTimeOffset(3)")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.ToTable("WebSession");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("QMSWebApplication.BackendServer.Data.Entities.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QMSWebApplication.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QMSWebApplication.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("QMSWebApplication.BackendServer.Data.Entities.Roles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QMSWebApplication.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QMSWebApplication.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
